#!/bin/sh
# DigiForge — Developed by Mikal
export APP_DIGIFORGE_STRATUM_PORT="3256"
export APP_DIGIFORGE_NERDMINER_STRATUM_PORT="3257"
export APP_DIGIFORGE_SCRYPT_STRATUM_PORT="3258"
export APP_DIGIFORGE_DGB_P2P_PORT="12024"
